// Package schema holds Go types that mirror the codex app-server JSON
// Schema bundle (`codex app-server generate-json-schema`). It is the
// statically typed surface that codexcli marshals into request params
// and unmarshals from notification payloads.
//
// The codex app-server emits one JSON Schema file per RPC method (~200
// files). Most are stable; the bundle ships v1 (initialize) and v2
// (everything else). This package currently hand-rolls the minimum
// surface needed for the first-pass demo: initialize, thread/start,
// turn/start, and the notifications between turn/started and
// turn/completed.
//
// The full type set will eventually be code-generated by the tool in
// `cmd/genschema`. Hand-written types stay until the generator lands.
package schema
